export const SHIPPING_RATES: Record<string, number> = {
  "kasbah el taher": 45,
  "lalla fatna": 45,
  "mehdia": 45,
  "ighram laalam-beni mellal": 45,
  "jamaat fdala": 35,
  "afra-nador": 45,
  "ahfir": 45,
  "ain attiq-temara": 45,
  "ain attiq": 45,
  "ait amira-agadir": 45,
  "amzmiz": 45,
  "anza": 40,
  "anzi-tiznit": 45,
  "arbaoua": 45,
  "asilah ville": 45,
  "azemmour": 45,
  "azilal ville": 45,
  "azilal": 45,
  "azro-ait melloul agadir": 40,
  "azrou-ville": 40,
  "afourar - beni-mellal": 45,
  "agadir": 35,
  "agafay": 45,
  "agdz": 45,
  "aghbal-berkan": 45,
  "aghbal": 45,
  "aghbala-beni mellal": 45,
  "aghbalou nserdan": 45,
  "aglou": 45,
  "agouim-ouarzazate": 45,
  "agouray - meknes": 45,
  "aguelmous": 45,
  "ahdil-chichaoua": 45,
  "ahmar laglalcha-taroudant": 45,
  "ain alla": 45,
  "ain allah-fes": 45,
  "ain aouda-temara": 45,
  "ain aouda": 45,
  "ain beida-chichaoua": 45,
  "ain bita-sefrou": 45,
  "ain bni mathar": 45,
  "ain cheggag": 45,
  "ain chkef": 45,
  "ain dfali-ouazzane": 45,
  "ain dorij": 45,
  "ain harouda": 30,
  "ain jemaa-meknes": 45,
  "ain mechlawa": 45,
  "ain sbit-khemisset": 45,
  "ain seddaq": 45,
  "ain tekki": 35,
  "ain zarka": 45,
  "ain el mediour": 45,
  "ain jiri-meknes": 45,
  "ait aissa oubrahim": 45,
  "ait baha": 45,
  "ait ben haddou-ouarzazate": 45,
  "ait hani-tinghir": 45,
  "ait iaaza": 45,
  "ait kamra-hoceima": 45,
  "ait melloul": 35,
  "ait ourir": 45,
  "ait zineb-ouarzazate": 45,
  "ait ishaq-khenifra": 45,
  "ait ishaq": 45,
  "ait ourir-marrakech": 45,
  "ajdir-houcima": 45,
  "ajdir-taza": 45,
  "akchour-chefchaouen": 45,
  "akchour": 45,
  "akhfennir": 45,
  "akka-tata": 45,
  "aklim": 45,
  "aknoul-taza": 45,
  "al hoceima": 45,
  "alnif": 45,
  "amerzgane-ouarzazate": 45,
  "amizmiz": 45,
  "aoufous": 45,
  "aoulouz": 45,
  "aourir-agadir": 45,
  "arba aounate": 45,
  "arjat-mohammedia": 35,
  "asif lmal-chichaoua": 45,
  "asni-marrakech": 45,
  "assa-ville": 45,
  "assa": 45,
  "assahrij-kelaa des sraghna": 45,
  "asseratou-chichaoua": 45,
  "attaouia": 45,
  "azla": 45,
  "azlaf-driouch": 45,
  "aïn erreggada": 45,
  "aït hadifa-al hoceima": 45,
  "aït ishaq": 45,
  "belksiri ville": 45,
  "belksiri": 45,
  "ben tayeb- driouch": 45,
  "berkan - ville": 45,
  "berrechid ville": 35,
  "bouarfa": 45,
  "boufkrane": 45,
  "bouknadel": 45,
  "bouknadl": 45,
  "bouskoura": 30,
  "bouznika": 40,
  "bab berred": 45,
  "bab marzouka-taza": 45,
  "bab taza": 45,
  "bani hadifa-al hoceima": 45,
  "bdouza": 45,
  "bejaad": 45,
  "belaagid": 45,
  "belfaa": 45,
  "ben ahmed": 45,
  "ben guerir": 45,
  "ben tayeb-nador": 45,
  "ben ahmed-berrchid": 45,
  "ben karich-tetouan": 45,
  "beni ensar": 45,
  "beni mellal": 40,
  "beni-hassan tetouan": 45,
  "beni-hassan-chefchaouen": 45,
  "benslimane": 35,
  "berkane": 45,
  "berrchid": 35,
  "bhalil-sefrou": 45,
  "bhalil": 45,
  "biougra": 45,
  "bir jdid": 35,
  "bir kouat": 45,
  "bir tam tam": 45,
  "bni ahmed - chefchaouen": 45,
  "bni ayat - beni-mellal": 45,
  "bni bouayach": 45,
  "bni boufrah-al hoceima": 45,
  "bni chiker": 45,
  "bni darkoul-chefchaouen": 45,
  "bni drar": 45,
  "bni wassine": 45,
  "bni yakhlef": 35,
  "bouderbala-meknes": 45,
  "boudnib": 45,
  "bouizakarne": 45,
  "bouizakarne-ville": 45,
  "boujdour": 45,
  "boujniba": 45,
  "boulanouare": 45,
  "boulemane-azrou": 45,
  "boumaln dads - tinghir": 45,
  "boumia": 45,
  "bounaamane-tiznit": 45,
  "bounouar-khouribga": 45,
  "boussmssad-meknes": 45,
  "bradia - beni-mellal": 45,
  "brych-asilah": 45,
  "chellalat": 35,
  "chrafat-chefchaouen": 45,
  "cabo negro": 45,
  "cap de l’eau": 45,
  "casablanca": 20,
  "chaibate-el jadida": 45,
  "chefchaouen": 45,
  "chemmaia-chichaoua": 45,
  "chichaoua-ville": 45,
  "chichaoua": 45,
  "chouiter": 45,
  "dar bouazza": 35,
  "dar el gadari": 45,
  "dar el kabdani-driouch": 45,
  "daroua": 35,
  "debdou": 45,
  "douar lkasit-nador": 45,
  "douar sakia": 45,
  "driouch ville": 45,
  "dakhla": 45,
  "daliya_ksar sghir": 45,
  "dar ould zidouh": 45,
  "dar el amri-sidi sliman": 45,
  "demnate ville": 45,
  "demnate-ville": 45,
  "demnate": 45,
  "derdara-chefchaouen": 45,
  "derdara-taroudant": 45,
  "dghaliyn-asilah": 45,
  "diki_ksar sghir": 45,
  "dkhissa-meknes": 45,
  "dlalha": 45,
  "douar boumaiz": 45,
  "douar rja fellah-nador": 45,
  "douar jdida-chichaoua": 45,
  "douar si omara-chichaoua": 45,
  "douiyat-fes": 45,
  "drarga": 45,
  "driouch-nador": 45,
  "el halhal mediouna": 35,
  "errachidia": 45,
  "errahma ville": 30,
  "essmara-sahara": 45,
  "echammaia-youssoufia": 45,
  "el borj-khenifra": 45,
  "el borouj-settat": 45,
  "el gara-berrchid": 45,
  "el jadida": 35,
  "el kbab - khénifra": 45,
  "el kebab-khenifra": 45,
  "el ksiba - beni-mellal": 45,
  "el maader el kabir-tiznit": 45,
  "el mansouria": 35,
  "el menzel - sefrou": 45,
  "el ouatia": 45,
  "tanger": 20,
  "el boura-taroudant": 45,
  "el houmer-taroudant": 45,
  "elhajeb ville": 45,
  "erfoud ville": 45,
  "essaouira": 45,
  "essemara": 45,
  "ezzhiliga": 45,
  "figuig": 45,
  "fam el hisn-tata": 45,
  "fes": 35,
  "fnideq": 45,
  "forina-chichaoua": 45,
  "foum oudi": 45,
  "foum zguid": 45,
  "fouwarat-meknes": 45,
  "fquih ben salah": 45,
  "fraita-kelaa des sraghna": 45,
  "gfifat": 45,
  "ghafsai": 45,
  "gouassem-ville": 45,
  "gouassem-marrakech": 45,
  "goulmima-errachidia": 45,
  "gourrama": 45,
  "guelmim-ville": 45,
  "guelmim": 45,
  "guercif": 45,
  "guigou-azrou": 45,
  "guisser-settat": 45,
  "had swlme": 45,
  "had wlad fraj": 45,
  "harhoura": 45,
  "hey mostawsaf": 45,
  "had draa": 45,
  "had hrara-safi": 45,
  "had kourt": 45,
  "had oulad aissa": 45,
  "had bouhssoussen": 45,
  "had lgharbiya-asilah": 45,
  "hadada – youssoufia": 45,
  "hadd ouled jelloul-kenitra": 45,
  "hadd ouled jelloul-tazi": 45,
  "harat el morabitine-tinghir": 45,
  "hattane-khouribga": 45,
  "houara": 45,
  "ieassen-nador": 45,
  "ifran": 45,
  "ighmariyin-nador": 45,
  "ihdaden-nador": 45,
  "imachrouben-nador": 45,
  "imeharfen-nador": 45,
  "imouzar kandre": 45,
  "isakkajen-nador": 45,
  "itzer": 45,
  "ighoud-chichaoua": 45,
  "imgon-tinghir": 45,
  "imi ouaddar-agadir": 45,
  "imintanoute": 45,
  "imintanoute-ville": 45,
  "imouzzer marmoucha": 45,
  "inzegane": 35,
  "issafen-tata": 45,
  "issaguen": 45,
  "jaadar-nador": 45,
  "jebha": 45,
  "jamaat riah-berrchid": 45,
  "jamaat foko-berrchid": 45,
  "jamaat shaim": 45,
  "jamaat larracha - kelaâ des sraghna": 45,
  "jaqma-berrchid": 45,
  "jebha-chefchaouen": 45,
  "jerada": 45,
  "jilaliya-asilah": 45,
  "jorf el melha-ouzzane": 45,
  "jorf sefar": 45,
  "jwala-kelaa des sraghna": 45,
  "kachadia-nador": 45,
  "keliaa": 45,
  "kenitra ville": 35,
  "khenifra ville": 45,
  "khenifra": 45,
  "kabila": 45,
  "kaf nsour-khenira": 45,
  "kariat arkman-nador": 45,
  "kariat ba mohamed": 45,
  "kasba tadla": 45,
  "kasba tadla-oulad yaich-benimellal": 45,
  "kasba tadla-oulad youssef-beni mellal": 45,
  "kasita-driouch": 45,
  "kelâa des sraghna": 45,
  "kelâat m gouna": 45,
  "ketama-houcima": 45,
  "khamis m diq-chefchaouen": 45,
  "khdadra-ksar el kbir": 45,
  "khemis sahel": 45,
  "khemisset ville": 45,
  "khenichet-sidi kacem": 45,
  "khlalfa-taounate": 45,
  "khnoufa – youssoufia": 45,
  "khouribga": 40,
  "khwalqa – youssoufia": 45,
  "kouassem-el jadida": 45,
  "ksar el kebir-laarch": 45,
  "ksar el kebir": 45,
  "ksar sghir-tanger": 45,
  "kwidar-meknes": 45,
  "laarjat": 40,
  "laarjate": 40,
  "laaroui": 45,
  "laayoune-playa": 45,
  "laayoune-port": 45,
  "lhaj kadour ville": 45,
  "lmhaya": 45,
  "lommal-nador": 45,
  "laayoune-sahara": 45,
  "laayoune-ville": 45,
  "lakhssas": 45,
  "lalla mimouna-kenitra": 45,
  "lalla mimouna": 45,
  "lalla takerkoust": 45,
  "lalla aziza-chichaoua": 45,
  "lamriss": 45,
  "laouamra": 45,
  "larache": 40,
  "layoun cherkia": 45,
  "laâtamna-kelaa des sraghna": 45,
  "laâtamna": 45,
  "lehri-khenifra": 45,
  "lhawzia-jadida": 45,
  "lhmadna-kelaa des sraghna": 45,
  "lmakina-chichaoua": 45,
  "lmnar park-ksar sghir": 45,
  "louihat – youssoufia": 45,
  "louizia": 35,
  "lozin-meknes": 45,
  "m diq": 45,
  "maamora": 35,
  "mdar": 45,
  "mehdia ville": 45,
  "mers el khir": 45,
  "mhamid el ghizlane": 45,
  "midelt": 45,
  "mkansa-mediouna": 35,
  "moly drisse zarhoune": 45,
  "moulay abdellah": 40,
  "maaziz": 45,
  "marghouba-asilah": 45,
  "marrakech": 35,
  "martil": 40,
  "marzouga": 45,
  "masmouda - ouazzane": 45,
  "massa": 45,
  "mazagan": 45,
  "mediouna": 35,
  "mejjat-chichaoua": 45,
  "mejjat-meknes": 45,
  "mejji-chichaoua": 45,
  "meknes": 35,
  "midar-driouch": 45,
  "mimosa-mohammedia": 35,
  "missour": 45,
  "mograne-tazi": 45,
  "mograne": 45,
  "mohammedia": 35,
  "moulay yaâcoub": 45,
  "moulay bouazza khenifra": 45,
  "mrirt ville": 45,
  "mrirt": 45,
  "mrirte": 45,
  "msawar raso": 45,
  "msemrir-tinghir": 45,
  "mzouda": 45,
  "mzoudia": 45,
  "nkob zagora": 45,
  "nador": 45,
  "nfifa-chichaoua": 45,
  "nouaceur": 35,
  "nowasser-chichaoua": 45,
  "nwinwich_ksar sghir": 45,
  "nzala-meknes": 45,
  "nzalat laadam-benguerir": 45,
  "ouahdana-nador": 45,
  "oualmes ville": 45,
  "oualmes": 45,
  "oudaya": 45,
  "oudaya-marrakech": 45,
  "oulad aissa-nador": 45,
  "ouled ben rahmoun": 45,
  "ouled salem-nador": 45,
  "oum azza": 40,
  "ouahat sidi brahim": 45,
  "ouaouizeght-azilal": 45,
  "ouaoumana": 45,
  "ouarzazat": 45,
  "ouazzane": 45,
  "oued amlil": 45,
  "oued laou": 45,
  "oued zem": 45,
  "oujda": 45,
  "oulad abbou-berrchid": 45,
  "oulad ayad": 45,
  "oulad berhil": 45,
  "oulad dahou": 45,
  "oulad hamdane-el jadida": 45,
  "oulad hammou-fes": 45,
  "oulad khallouf -kelaa des sraghna": 45,
  "oulad m barek-beni mellal": 45,
  "oulad said-beni mellal": 45,
  "oulad said-settat": 45,
  "oulad salah-bouskoura": 35,
  "oulad sbaita-assilah": 45,
  "oulad tayeb-fes": 45,
  "oulad teima": 45,
  "oulad yaïch-chichaoua": 45,
  "oulad zmam - beni-mellal": 45,
  "oulad brahim-taroudant": 45,
  "oulad hassoun-marrakech": 45,
  "ouled boutabet": 45,
  "ouled moussa-beni mellal": 45,
  "ouled riahi-assilah": 45,
  "ourika-ville": 45,
  "ourika": 45,
  "outat el haj": 45,
  "poblaw-nador": 45,
  "plage david-bouznika": 35,
  "quartier al boustane-nador": 45,
  "riche-02": 45,
  "rissani ville": 45,
  "rommani ville": 45,
  "rommani": 45,
  "rouissi-nador": 45,
  "rabat": 35,
  "ras el ain – youssoufia": 45,
  "ras el ma-fes": 45,
  "ras el ma-nador": 45,
  "ras el ma-berkan": 45,
  "ras tabouda": 45,
  "ribate el kheir": 45,
  "rouadi-al hoceima": 45,
  "saaidia": 45,
  "sale": 35,
  "sebt gzoula": 45,
  "sefrou": 45,
  "sidi ifni-ville": 45,
  "sidi ifni": 45,
  "sidi kacem": 40,
  "sidi kaml": 45,
  "sidi rahle": 40,
  "sidi sliman": 45,
  "sidi yahya gharb ville": 45,
  "sidi yahya gharb": 45,
  "skhirat": 45,
  "souk larbaa ville": 45,
  "souk larbaa": 45,
  "souk lhad allal tazi": 45,
  "stehat-oued laou": 45,
  "swasiyin alal tazi": 45,
  "safi": 40,
  "salama-ksar el kbir": 45,
  "sale el jadida-سلا": 35,
  "sale el jadida": 35,
  "samba-chichaoua": 45,
  "sbaa ayoune": 45,
  "sbiaat – youssoufia": 45,
  "sebt el guerdane": 45,
  "sebt jahjouhe-meknes": 45,
  "sebt saiss": 45,
  "segangan-nador": 45,
  "selouane": 45,
  "settat-ville": 40,
  "settat": 40,
  "settate": 40,
  "sfassif-khemisset": 45,
  "sid l mokhtar": 45,
  "sid zouine": 45,
  "sidi abbad": 45,
  "sidi aissa ben slimane-kelaa des sraghna": 45,
  "sidi aissa-beni-mellal": 45,
  "sidi al kamel-tazi": 45,
  "sidi al kamel": 45,
  "sidi allal el bahraoui": 45,
  "sidi allal tazi": 45,
  "sidi ayache": 45,
  "sidi bennour": 45,
  "sidi bou othmane-ville": 45,
  "sidi bou othmane": 45,
  "sidi bouzid-el jadida": 45,
  "sidi bouzid-safi": 45,
  "sidi chiker – youssoufia": 45,
  "sidi chiker": 45,
  "sidi ghiat": 45,
  "sidi hajjaj-berrchid": 45,
  "sidi harazem": 45,
  "sidi kaouki-essouira": 45,
  "sidi kaouki": 45,
  "sidi moussa ben ali": 40,
  "sidi moussa el majdoub": 40,
  "sidi rahhal": 35,
  "sidi taibi": 45,
  "sidi yahya zaer": 45,
  "sidi zouine-chichaoua": 45,
  "sidi ali ben hamdoch-jadida": 45,
  "sidi lyamani-asilah": 45,
  "sidi moussa lhamri-taroudant": 45,
  "sidi-bibi": 45,
  "skhinate-fes": 45,
  "skhour rehamna": 45,
  "skoura-ouarzazate": 45,
  "smimou - essaouira": 45,
  "smimou-essouira": 45,
  "souihla-ville": 45,
  "souihla": 45,
  "souiria": 45,
  "souk sebt oulad nemma": 45,
  "souk tlata tanquoub ouazzane": 45,
  "souk tlet el gharb": 45,
  "souk al had ouazzane": 45,
  "souk lgor-meknes": 45,
  "stehat-chefchaouen": 45,
  "tamaris": 35,
  "tamesna-temara": 45,
  "tanante-azilal": 45,
  "tantan": 45,
  "taouima-nador": 45,
  "tawjtat": 45,
  "taza-ville": 45,
  "temara": 35,
  "tighmi-tiznit": 45,
  "tit mellil": 30,
  "tiznit": 40,
  "tnin el ghiate-safi": 45,
  "taddart-taza": 45,
  "tafetachte essaouira": 45,
  "tafetachte-chichaoua": 45,
  "tafoughalt": 45,
  "tafraoute": 45,
  "tafrsit-driouch": 45,
  "taghazout": 45,
  "taghzot- tinghir ville": 45,
  "tagmout-tata": 45,
  "tagounite-zagora": 45,
  "tahadart - asilah": 45,
  "tahanaout-ville": 45,
  "tahanaout": 45,
  "tahla": 45,
  "taliouine": 45,
  "talmest": 45,
  "tamait izder-agadir": 45,
  "tamanar-essouira": 45,
  "tamanar-essaouira": 45,
  "tamansourt-marrakech": 45,
  "tamansourt": 45,
  "tamegroute-zagora": 45,
  "tamellalt": 45,
  "tamesluht- ville": 45,
  "tamesluht": 45,
  "tamesna": 45,
  "tamraght-agadir": 45,
  "tamraght": 45,
  "tamri-agadir": 45,
  "tamzmout zagora": 45,
  "tan tan": 45,
  "tanougha-beni mellal": 45,
  "taounate-fes": 45,
  "taourirt": 45,
  "tarfaya ville": 45,
  "tarfya": 45,
  "taroudant": 40,
  "tassawt-kelaa des sraghna": 45,
  "tassoultant-ville": 45,
  "tassoultante": 45,
  "tata": 45,
  "taza": 45,
  "tazarine": 45,
  "taznakht": 45,
  "temsia-agadir": 45,
  "teroual - ouazzane": 45,
  "tetouan": 35,
  "tiflet ville": 45,
  "tighassaline ville": 45,
  "tighassaline": 45,
  "tikiouine": 35,
  "timahdite": 45,
  "timoulilt-béni mellal": 45,
  "tin mansour": 45,
  "tindafel-assilah": 45,
  "tinejdad ville": 45,
  "tinghir ville": 45,
  "tioughza": 45,
  "tissint-tata": 45,
  "tizi ousli": 45,
  "tiztotin-nador": 45,
  "tiztotine-driouch": 45,
  "tlat bouaris": 45,
  "tlat loulad-fini": 45,
  "tlat lghnimiyin-berrchid": 45,
  "tlet el hanchane": 45,
  "tleta bouguedra": 45,
  "tnin beni khelloug-settat": 45,
  "tnin jnan bih-chichaoua": 45,
  "tnine chtouka el jadida": 45,
  "tnine gharbia": 45,
  "toundout-ouarzazet": 45,
  "tounfite-midelt": 45,
  "tīdās-khemisset": 45,
  "wad lmarssa": 45,
  "wadalyane_ksar sghir": 45,
  "walidia": 45,
  "wlad ghanem": 45,
  "wlad amer alal tazi": 45,
  "wlad amer-alal tazi": 45,
  "wlad sidi yhya-meknes": 45,
  "youssoufia-rabat": 35,
  "youssoufia-ville": 45,
  "zagora": 45,
  "zgouta": 45,
  "zag-ville": 45,
  "zag": 45,
  "zaida": 45,
  "zaouiat bougrine": 45,
  "zaouiat cheikh": 45,
  "zaouit sidi smail": 45,
  "zouada-laarache": 45,
  "zoumi-ouazzane": 45,
  "aazayeb-chefchaouen": 45,
  "agzirt beni-mellal": 45,
  "ain aicha - taounate": 45,
  "ain leuh": 45,
  "ain mediouna - taounate": 45,
  "aine aghbal-meknes": 45,
  "ait ai3zam-meknes": 45,
  "ait ihya omoussa": 45,
  "akrach-rabat": 45,
  "beni elouida-azilal": 45,
  "beni elouida-benimellal": 45,
  "beni oulid - taounate": 45,
  "bouanane-tetoun": 45,
  "bouanga-chichaoua": 45,
  "bouhouda - taounate": 45,
  "boukidan": 45,
  "boulemane-midelte": 45,
  "chouiter-marrakech": 45,
  "dcheira": 45,
  "douar zliligue-fes": 45,
  "ferkhana-nador": 45,
  "foum jamaa-azilal": 45,
  "galaz - taounate": 45,
  "had soualem": 35,
  "hajria - taounate": 45,
  "idi jaber-beni-mellal": 45,
  "ighram-taroudant": 45,
  "ighrem nougdal-ouarzazate": 45,
  "iminifri - kelaa des sraghna": 45,
  "imouzzar marmoucha-azrou": 45,
  "imsouane-agadir": 45,
  "imzouren": 45,
  "kamouni": 45,
  "kantra askar - taounate": 45,
  "khemis zemamra": 45,
  "khzana-chefchaouen": 45,
  "ksar sghir": 45,
  "lkhyayta-had soualem": 35,
  "marina smir": 45,
  "massa-agadir": 45,
  "mezraoua - taounate": 45,
  "mirleft": 45,
  "moulay bousselham": 45,
  "nouail-taroudant": 45,
  "oulad ali-fkih bensaleh-beni mellal": 45,
  "oulad jerrar-tiznit": 45,
  "oulad mhela-taroudant": 45,
  "oulad terna-taroudant": 45,
  "ounagha": 45,
  "ourtzagh - taounate": 45,
  "ouzioua": 45,
  "sebt malha-chefchaouen": 45,
  "sehoul-sale": 45,
  "sidi aadi - azrou": 45,
  "sidi el aidi-berrchid": 45,
  "sidi el aidi-settat": 45,
  "sidi el makhfi - taounate": 45,
  "sidi hajjaj-casa": 35,
  "sidi ouaaziz": 45,
  "sidi yahia elgharb": 45,
  "snadla-ksar el kbir": 45,
  "tahar souk - taounate": 45,
  "tamaloukt-taroudant": 45,
  "tanant-azilal": 45,
  "taounate": 45,
  "targuist": 45,
  "tazmourt-taroudant": 45,
  "temsamane-driouch": 45,
  "temsamane-houcima": 45,
  "tissa - taounate": 45,
  "tizi nisly-beni mellal": 45,
  "tnin beni onjel - taounate": 45,
  "tohmo agadir": 45,
  "ville test site": 45,
  "wargi-kelaa sraghna": 45,
  "wislan-meknes": 45,
  "wlad slim-meknes": 45,
  "zayou": 45,
  "zrizer - taounate": 45
};

// Function to normalize strings for comparison (remove accents, lowercase, trim)
const normalizeCity = (city: string): string => {
  return city
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
};

export const getDeliveryFee = (city: string): number => {
  const normalizedInput = normalizeCity(city);
  
  // Check for exact match first
  if (SHIPPING_RATES[normalizedInput]) {
    return SHIPPING_RATES[normalizedInput];
  }
  
  // Fallback: check if any key contains the input (simple fuzzy search)
  // or if the input contains a key (e.g., input "Tanger Ville" matches key "tanger")
  /* 
    WARNING: Simple includes can be dangerous (e.g. "Sale" matching "Salé").
    Given the specific list, exact match on the normalized keys is safest.
    If not found, we default to the most common price (45).
  */
 
  return 45;
};

export const getCityList = (): string[] => {
    return Object.keys(SHIPPING_RATES).sort();
}
